# Generated by Django 5.2.6 on 2025-10-03 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('excerpt', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blogs/')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(db_index=True, max_length=200)),
                ('sender', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('patch_type', models.CharField(choices=[('embroidered', 'Embroidered'), ('chenille', 'Chenille'), ('pvc', 'PVC'), ('woven', 'Woven'), ('custom', 'Custom/Stickers')], max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('backing_type', models.CharField(choices=[('Sew-On', 'Sew-On'), ('Iron-On', 'Iron-On'), ('Velcro/Hook', 'Velcro/Hook'), ('Adhesive Sticker', 'Adhesive Sticker')], max_length=50)),
                ('artwork', models.FileField(upload_to='artwork/')),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('title', models.CharField(blank=True, max_length=250)),
                ('body', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='PatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('patch_type', models.CharField(choices=[('embroidered', 'Embroidered'), ('chenille', 'Chenille'), ('pvc', 'PVC'), ('woven', 'Woven'), ('custom', 'Custom/Stickers')], max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('backing_type', models.CharField(choices=[('Sew-On', 'Sew-On'), ('Iron-On', 'Iron-On'), ('Velcro/Hook', 'Velcro/Hook'), ('Adhesive Sticker', 'Adhesive Sticker')], max_length=50)),
                ('artwork', models.FileField(upload_to='artwork/')),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SliderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(upload_to='sliders/')),
                ('cta_text', models.CharField(blank=True, max_length=80)),
                ('cta_url', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_images/')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='api.service')),
            ],
        ),
    ]
