# Generated by Django 5.2.6 on 2026-02-11 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Short summary, used for SEO and previews.')),
                ('content', models.TextField()),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                ('meta_title', models.CharField(blank=True, help_text='Auto-generated if blank', max_length=500)),
                ('meta_description', models.CharField(blank=True, help_text='Auto-generated if blank', max_length=500)),
                ('meta_keywords', models.CharField(blank=True, help_text='Auto-generated if blank', max_length=1500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150, unique=True)),
                ('assigned_admin', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('patch_type', models.CharField(choices=[('embroidered', 'Embroidered'), ('leather', 'Leather'), ('chenille', 'Chenille'), ('printed', 'Printed'), ('pvc', 'PVC'), ('woven', 'Woven'), ('custom', 'Custom / Stickers')], max_length=50)),
                ('embroidery_coverage', models.CharField(blank=True, choices=[('50%', '50% Embroidered'), ('75%', '75% Embroidered'), ('100%', '100% Embroidered')], max_length=10, null=True)),
                ('dimension', models.CharField(blank=True, choices=[('2D', '2D Mold'), ('3D', '3D Mold')], max_length=2, null=True)),
                ('unit', models.CharField(choices=[('inches', 'Inches'), ('mm', 'Millimeters'), ('cm', 'Centimeters')], default='inches', max_length=20)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('shape', models.CharField(choices=[('custom', 'Custom Shape'), ('circle', 'Circle'), ('square', 'Square'), ('h-oval', 'Horizontal Oval'), ('h-rect', 'Horizontal Rectangle'), ('v-rect', 'Vertical Rectangle'), ('diamond', 'Diamond'), ('v-oval', 'Vertical Oval'), ('shield-a', 'Shield A'), ('shield-b', 'Shield B'), ('shield-c', 'Shield C'), ('shield-d', 'Shield D')], default='custom', max_length=30)),
                ('backing', models.CharField(choices=[('none', 'No Backing'), ('iron', 'Iron-on'), ('adhesive', 'Adhesive'), ('plastic', 'Plastic'), ('velcro-hook', 'Velcro Hook'), ('velcro-loop', 'Velcro Loop'), ('velcro-both', 'Velcro Hook & Loop'), ('safety-pin', 'Safety Pin')], default='none', max_length=30)),
                ('border', models.CharField(blank=True, choices=[('merrow', 'Merrow'), ('heat-cut', 'Heat Cut'), ('laser-cut', 'Laser Cut')], max_length=30, null=True)),
                ('thread', models.CharField(choices=[('normal', 'Normal'), ('gold', 'Gold Metallic'), ('silver', 'Silver Metallic'), ('glow', 'Glow in the Dark')], default='normal', max_length=20)),
                ('leather_type', models.CharField(blank=True, choices=[('genuine', 'Genuine Leather'), ('faux', 'Faux Leather'), ('suede', 'Suede Finish'), ('rustic', 'Rustic / Polished')], max_length=20, null=True)),
                ('finish_effect', models.CharField(blank=True, choices=[('embossed', 'Embossed'), ('debossed', 'Debossed'), ('engraving', 'Engraving'), ('printed', 'Printed')], max_length=20, null=True)),
                ('quantity', models.CharField(blank=True, choices=[('10', '10'), ('25', '25'), ('50', '50'), ('75', '75'), ('100', '100'), ('150', '150'), ('300', '300'), ('500', '500'), ('1000', '1000'), ('3000', '3000'), ('5000+', '5000+')], max_length=20, null=True)),
                ('custom_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True)),
                ('description', models.TextField()),
                ('meta_title', models.CharField(blank=True, help_text='Auto-generated if blank', max_length=500)),
                ('meta_description', models.CharField(blank=True, help_text='Auto-generated if blank', max_length=500)),
                ('meta_keywords', models.CharField(blank=True, help_text='Auto-generated if blank', max_length=1500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SliderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(upload_to='sliders/')),
                ('cta_text', models.CharField(blank=True, max_length=80)),
                ('cta_url', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='uploads/chat_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], max_length=20)),
                ('sender_name', models.CharField(blank=True, max_length=150, null=True)),
                ('message', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='chat_attachments/')),
                ('is_read_by_admin', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.chatroom')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255, unique=True)),
                ('volume', models.PositiveIntegerField(default=0, help_text='Monthly USA search volume estimate')),
                ('competition', models.FloatField(default=0.0, help_text='0–1 scale (lower = easier to rank)')),
                ('intent', models.CharField(choices=[('informational', 'Informational'), ('commercial', 'Commercial'), ('transactional', 'Transactional')], default='commercial', max_length=20)),
                ('pillar', models.CharField(blank=True, choices=[('general', 'General / Core Keywords'), ('embroidered', 'Embroidered Patches'), ('pvc', 'PVC Patches'), ('leather', 'Leather Patches'), ('chenille', 'Chenille Patches'), ('guides', 'Design & Buying Guides')], max_length=50)),
                ('target_url', models.CharField(blank=True, help_text='Internal URL this keyword should target', max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clusters', to='api.keyword')),
            ],
            options={
                'verbose_name_plural': 'Keywords',
                'ordering': ['-volume', 'term'],
            },
        ),
        migrations.CreateModel(
            name='PatchArtwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='artwork/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='api.patchrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_images/')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='api.service')),
            ],
        ),
    ]
