# Generated by Django 5.2.6 on 2025-10-07 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patchrequest',
            name='artwork',
        ),
        migrations.RemoveField(
            model_name='patchrequest',
            name='backing_type',
        ),
        migrations.RemoveField(
            model_name='patchrequest',
            name='size',
        ),
        migrations.AddField(
            model_name='patchrequest',
            name='backing',
            field=models.CharField(choices=[('none', 'No Backing'), ('iron', 'Iron on'), ('adhesive', 'Adhesive'), ('plastic', 'Plastic'), ('velcro-hook', 'Velcro Hook Backing'), ('velcro-loop', 'Velcro Loop Backing'), ('velcro-both', 'Velcro Hook & Loop Backing'), ('safety-pin', 'Safety Pin')], default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='patchrequest',
            name='border',
            field=models.CharField(blank=True, choices=[('merrow', 'Merrow'), ('heat-cut', 'Heat Cut'), ('laser-cut', 'Laser Cut')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='patchrequest',
            name='custom_qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patchrequest',
            name='embroidery_coverage',
            field=models.CharField(blank=True, choices=[('50%', '50% Embroidered'), ('75%', '75% Embroidered'), ('100%', '100% Embroidered')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patchrequest',
            name='height',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='patchrequest',
            name='shape',
            field=models.CharField(choices=[('custom', 'Custom Shape'), ('circle', 'Circle'), ('square', 'Square'), ('h-oval', 'Horizontal Oval'), ('h-rect', 'Horizontal Rectangle'), ('v-rect', 'Vertical Rectangle'), ('diamond', 'Diamond'), ('v-oval', 'Vertical Oval'), ('shield-a', 'Shield A'), ('shield-b', 'Shield B'), ('shield-c', 'Shield C'), ('shield-d', 'Shield D')], default='custom', max_length=30),
        ),
        migrations.AddField(
            model_name='patchrequest',
            name='thread',
            field=models.CharField(choices=[('normal', 'Normal'), ('gold', 'Gold Metallic'), ('silver', 'Silver Metallic'), ('glow', 'Glow in the Dark')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='patchrequest',
            name='unit',
            field=models.CharField(choices=[('inches', 'Inches'), ('mm', 'Millimeters'), ('cm', 'Centimeters')], default='inches', max_length=20),
        ),
        migrations.AddField(
            model_name='patchrequest',
            name='width',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='patchrequest',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='patchrequest',
            name='patch_type',
            field=models.CharField(choices=[('embroidered', 'Embroidered'), ('leather', 'Leather'), ('chenille', 'Chenille'), ('printed', 'Printed'), ('pvc', 'PVC'), ('woven', 'Woven'), ('custom', 'Custom/Stickers')], max_length=50),
        ),
        migrations.AlterField(
            model_name='patchrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='patchrequest',
            name='quantity',
            field=models.CharField(blank=True, choices=[('10', '10'), ('25', '25'), ('50', '50'), ('75', '75'), ('100', '100'), ('150', '150'), ('300', '300'), ('500', '500'), ('1000', '1000'), ('3000', '3000'), ('5000+', '5000+')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='PatchArtwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='artwork/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='api.patchrequest')),
            ],
        ),
    ]
