# Generated by Django 5.2.6 on 2025-10-13 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150, unique=True)),
                ('assigned_admin', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp']},
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='artwork',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='backing_type',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='patch_type',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='size',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='text',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_read_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.chatroom'),
        ),
    ]
