# Generated by Django 5.2.6 on 2025-12-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_uploadedimage_chatfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='patchrequest',
            name='dimension',
            field=models.CharField(blank=True, choices=[('2D', '2D Mold'), ('3D', '3D Mold')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='patchrequest',
            name='finish_effect',
            field=models.CharField(blank=True, choices=[('embossed', 'Embossed'), ('debossed', 'Debossed'), ('engraving', 'Engraving'), ('printed', 'Printed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patchrequest',
            name='leather_type',
            field=models.CharField(blank=True, choices=[('genuine', 'Genuine Leather'), ('faux', 'Faux Leather'), ('suede', 'Suede Finish'), ('rustic', 'Rustic / Polished')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patchrequest',
            name='backing',
            field=models.CharField(choices=[('none', 'No Backing'), ('iron', 'Iron-on'), ('adhesive', 'Adhesive'), ('plastic', 'Plastic'), ('velcro-hook', 'Velcro Hook'), ('velcro-loop', 'Velcro Loop'), ('velcro-both', 'Velcro Hook & Loop'), ('safety-pin', 'Safety Pin')], default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='patchrequest',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='patchrequest',
            name='patch_type',
            field=models.CharField(choices=[('embroidered', 'Embroidered'), ('leather', 'Leather'), ('chenille', 'Chenille'), ('printed', 'Printed'), ('pvc', 'PVC'), ('woven', 'Woven'), ('custom', 'Custom / Stickers')], max_length=50),
        ),
        migrations.AlterField(
            model_name='patchrequest',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
