# Generated by Django 5.2.6 on 2026-02-06 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_service_created_at_service_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255, unique=True)),
                ('volume', models.PositiveIntegerField(default=0, help_text='Monthly USA search volume estimate')),
                ('competition', models.FloatField(default=0.0, help_text='0–1 scale (lower = easier to rank)')),
                ('intent', models.CharField(choices=[('informational', 'Informational'), ('commercial', 'Commercial'), ('transactional', 'Transactional')], default='commercial', max_length=20)),
                ('pillar', models.CharField(blank=True, choices=[('embroidered', 'Embroidered Patches'), ('pvc', 'PVC Patches'), ('leather', 'Leather Patches'), ('chenille', 'Chenille Patches'), ('guides', 'Design & Buying Guides')], max_length=50)),
                ('target_url', models.CharField(blank=True, help_text='Internal URL this keyword should target', max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clusters', to='api.keyword')),
            ],
            options={
                'verbose_name_plural': 'Keywords',
                'ordering': ['-volume', 'term'],
            },
        ),
    ]
