# Generated by Django 5.2.6 on 2026-02-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='pillar',
            field=models.CharField(blank=True, choices=[('general', 'General / Core Keywords'), ('embroidered', 'Embroidered Patches'), ('pvc', 'PVC Patches'), ('leather', 'Leather Patches'), ('chenille', 'Chenille Patches'), ('guides', 'Design & Buying Guides')], max_length=50),
        ),
    ]
