# Generated by Django 5.2.6 on 2026-02-06 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_keyword_pillar'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 6, 9, 57, 29, 769813, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Auto-generated if blank', max_length=160),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Auto-generated if blank', max_length=250),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Auto-generated if blank', max_length=150),
        ),
        migrations.AlterField(
            model_name='service',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Auto-generated if blank', max_length=160),
        ),
        migrations.AlterField(
            model_name='service',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Auto-generated if blank', max_length=250),
        ),
        migrations.AlterField(
            model_name='service',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Auto-generated if blank', max_length=150),
        ),
    ]
