# Generated by Django 5.2.6 on 2026-02-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_blogpost_created_at_blogpost_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Auto-generated if blank', max_length=500),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Auto-generated if blank', max_length=500),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Auto-generated if blank', max_length=500),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Auto-generated if blank', max_length=500),
        ),
        migrations.AlterField(
            model_name='service',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Auto-generated if blank', max_length=500),
        ),
        migrations.AlterField(
            model_name='service',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Auto-generated if blank', max_length=500),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, unique=True),
        ),
    ]
