# Generated by Django 5.2.6 on 2026-02-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_blogpost_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Auto-generated if blank', max_length=1500),
        ),
        migrations.AlterField(
            model_name='service',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Auto-generated if blank', max_length=1500),
        ),
    ]
